#!/usr/bin/env bash
# Cross-compiles and packages every firmware/ binary using the same
# devkitpro/devkita64 Docker image CI uses - no local devkitPro/libnx install
# needed. See AGENTS.md Rule #3 for the manual equivalent of each step.
#
# Usage: scripts/build-firmware.sh [--dist]
#   --dist   also assemble dist/ as an SD-card-ready tree (atmosphere/contents/...,
#            switch/nxremoteapi.nro) for direct FTP upload.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE="devkitpro/devkita64:latest"
UID_GID="$(id -u):$(id -g)"

run() {
    docker run --rm --user "$UID_GID" -v "$REPO_ROOT":/app -w /app "$IMAGE" /bin/bash -c "$1"
}

echo "==> core (exefs.nsp)"
run "cd firmware/core && make clean && make pack"

echo "==> orchestrator (exefs.nsp)"
run "cd firmware/orchestrator && make clean && make pack"

echo "==> companion-app (.nro)"
run "cd firmware/companion-app && make clean && make"

echo "==> companion-app launcher (.nso, experimental/paused - see ADR-0009 and AGENTS.md Rule #5)"
run "cd firmware/companion-app && make launcher"

echo "==> firmware/common host test suite (Catch2, no devkitA64 needed)"
docker run --rm --user "$UID_GID" -v "$REPO_ROOT":/app -w /app/firmware/common/tests gcc:latest \
    /bin/bash -c "make clean >/dev/null 2>&1; make && ./run_tests"

if [[ "${1:-}" == "--dist" ]]; then
    echo "==> assembling dist/ (SD-card-ready layout)"
    DIST="$REPO_ROOT/dist"
    rm -rf "$DIST"
    mkdir -p \
        "$DIST/atmosphere/contents/010000000000CAFE" \
        "$DIST/atmosphere/contents/010000000000CAF0/flags" \
        "$DIST/switch" \
        "$DIST/config/NXRemoteAPI"
    cp "$REPO_ROOT/firmware/core/exefs.nsp" "$DIST/atmosphere/contents/010000000000CAFE/exefs.nsp"
    cp "$REPO_ROOT/firmware/orchestrator/exefs.nsp" "$DIST/atmosphere/contents/010000000000CAF0/exefs.nsp"
    cp "$REPO_ROOT/firmware/orchestrator/boot2.flag" "$DIST/atmosphere/contents/010000000000CAF0/flags/boot2.flag"
    cp "$REPO_ROOT/firmware/companion-app/nxremoteapi.nro" "$DIST/switch/nxremoteapi.nro"
    echo "dist/ ready - copy dist/atmosphere and dist/switch onto the SD card root."
    echo "dist/config/NXRemoteAPI is empty on purpose: settings.json is generated by"
    echo "core on first boot (or migrate an existing one - see AGENTS.md Rule #5)."
fi

echo "==> done"
