name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: |
          uv pip install .[test]
          
      - name: Run tests
        run: |
          uv run pytest --durations=10

  build-sysmodule:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Sysmodule
        run: |
          export PATH=$PATH:/opt/devkitpro/devkitA64/bin:/opt/devkitpro/tools/bin
          export DEVKITPRO=/opt/devkitpro
          cd switch_sysmodule
          make
